'''
Created on Aug 26, 2015

@author: sarraju
'''
import wx
class Resourcer():
    def __init__(self, parent):
        self.parent = parent
        
    def getBitMapImg(self, code = "DEFAULT"):
        from cStringIO import StringIO
        img = wx.EmptyImage()
        
        if code == "UI_AUTH":
            str_ui_auth="iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAzklEQVR42mNkIA4wATEbEP9Al2AkoJETiDuBWBaIvwKxIJR/iFgDFgHxXCA+iGQgSKwZiC8RMkAFiHOBOB9NXBJqQAohA9yBWAqI52ORWwfEQcQYIAHEC7HIrQfiQFwGsEKdaAT18x0sapyAeA/IddgMMAVifyDuJhDALEA8FZsB5kDswACJLkJgObEGhEFdlQrE38gxYAkQRwCxOhDfJceAdCCuZ4BEK1lekANia5AGcg0gKRB1gbgM6m98AJRewnGlRC8gFiVgwH8g3g0Akjkmm+qaGHoAAAAASUVORK5CYII="
            img.LoadStream(StringIO(str_ui_auth.decode('base64')))
            del str_ui_auth
            return wx.StaticBitmap(self.parent, -1, wx.BitmapFromImage(img))
        elif code == "MSG_WARN":
            msg_warn = "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABmJLR0QA/wD/AP+gvaeTAAAEJ0lEQVRIx7WUz24TVxTGf+fcmczYxHZFS4gUwSIBbCqkLugmdEOlVhFSpdKKN4BNXqAP0W3WvAEqrZpKIGjFhnZFhVRaSBOzgAZFCEIdJ/6TmXtPF7ZjG5KyaY80uvPn3vnO953zHfifQ/Z7uTo3h5gBSB5FsnrsWDi+sUGc5yCCjyI2p6eZevpUNc8NMESorq39O8CD06dpOcfRbpftKFI1I83z8E6nIy8KhWhX1ZkZUbfrK8+e5e2jRy0rFhUzSJJAowFJMgYUjQJoCEyGQAf0cKMRvOpks1g8v3Ho0JdmNi8wIyJYkqz/PTv7s8H1tNW6oyFsd0BDsRgOZLB28iRpntOOY8kmJsyHcDbK86+Bj01kb9/ILZiZmP2E2Ve7hcKvYibtUsmSVosP7t8fAjyfmgLgVbmseRQFMftM4KrBFOD7+4QQRERAtad773KYPTe4DCyLmUZ5HgBOPn6M/F6rDVJzJuKBD533N4B3DTKBGMBCIL1yBYDO1auI6oBHBsSYvRTvF8Tsnqm63Dm/x2B1bk7KOzsGFF6Vy9eD6gKQYRYzkCTPKV+7BiJsXbqERBEGiBmDRMTsZtJoXAQ6u5OTUl1bs+hBrYb3Xl6VSmYinwALmHmB2IZagwjW6exbwD5LDyx0yuVPXQjfIyK/1WqmkRlV1bCtCiIXrZex2NifZLgOpXmjYUwERD73hQJhdTVEZqiZ8af3lPM8xuzcoFXGuuWAsPF1kNRHUbMZ69wcmBGZCN45AAfM9CUZZ2D9pzDe5jK+ivTAZrpx7EQkE5Ge0cwMM0NVeSPzHm0sBKRcfiur1yMSM8R78N6TJOtArc9aBl0yAMpu3RooOGQ1rpgIrLss8zgHzqEC1Op1ssOHM4G7o7KOchFV2ktLtJeWDir0APEupVJGvQ4iaO4cK6dO6cT2NgG+62dmoyegZ7TC4iLp4iIWwv4APU98K90uUq2qF0HPPHyIhGDJ1haFRuOWwM1+wTMZqQFmxPPzTMzP7/mCYb0ywAncKOzs3E5aLSQEO/Po0XBUOO+dmHmDs+bcTUTGR4UZbnq610wbG6//PDZ46bxfAO6ZiPO9sdOTeb1/sFkqqXdub9ghMjbsbHe3R2piYmzYGTzH7LKJLKuZJv1hN1uvowAzGxu8mJ5m68iREOJY8iRZlhAuSAg/YqaAGoikKZKmg8QUM8Xstnh/oRNFyxZF0i2VQqtYZLZeH/MKAH9UqwBoCJq22yGoTnbS9DwiXwics54RTWAd+CWYfVPMsjsawk47STSIBID3V1aGPhgFcN7jvSdOktBNUxWRVqnbXX6v2fzhr0ol6kSREyDKc1/Z2sqblYrtpKlqCNqoVMLxJ09olkrjPt2v31ZOnNj7bqrSnZoKE5ubiPcEwKuyOTnJVKOhajaoBdXV1bdb+7+OfwCUrAsufau7dwAAAABJRU5ErkJggg=="
            img.LoadStream(StringIO(msg_warn.decode('base64')))
            del  msg_warn
            return wx.StaticBitmap(self.parent, -1, wx.BitmapFromImage(img))            
        elif code == "MSG_OK":
            msg_ok = "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAJI0lEQVRIDQEYCef2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJsAlUCK8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABq5GgwFrwWlAa0B8wu0CzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABG1ERoDrgPNAK0A+QuyC0gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6zDiQCrgLfAK0A/wmxCWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+yDyYCrQLlAK0A/wawBpUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABC0EB4CrgLhAKwA/wOuA8kivCIGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHsAeJBa8Frxm5GQwAAAAAAAAAABa3FhADrgPVAK0A/wGtAfEPtA8kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABa8FqwCsAP8CrgLVDrMOKkPJQwIErwS3AKwA/wCsAP8JsQliAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABi4GA4CrgLdAK0A/wGtAfcFrwWzAKwA/wCsAP8ErwS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLMMOgCtAPsArQD/AK0A/wCtAP8BrQHzELUQHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHsAeDAKwA/wCsAP8ArAD/B7AHcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJb0lBgOuA80ArQD/A64D0SrBKgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOtA4qAa0B9QyzDD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABK2EjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjghedWNer2MAAAAASUVORK5CYII="
            img.LoadStream(StringIO(msg_ok.decode('base64'))) 
            del msg_ok
            return wx.StaticBitmap(self.parent, -1, wx.BitmapFromImage(img))
        elif code == "FILE_ICON":
            file_icon = "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMBAJqcGAAAAMlJREFUOI2d0zFqQkEYBOBPsfEGBlJKytjbWKYMiIW5SiRgSDyJjYWNJ5CAF4hobRsPIIKIWCzGh+z6fE61uzPMDv/slpzxhA9UxTHEJMH9C2oJrosl2pdEObOu4u/KBZ94uTQpx7VRNPGDAV6LGkwxw06Y01tMNC6QZlQ0QRKVyNkz3hP6L6GNqwZzoba7EzygldBPsc4zOGCfMDjckmCtQCMxg4bQdQx9LPIMftG5NUH2HWyFAebhEZvTppQh6uhJf+cTNvjGCo5Fhx7hZo7d6QAAAABJRU5ErkJggg=="
            img.LoadStream(StringIO(file_icon.decode('base64')))
            del file_icon
            return wx.BitmapFromImage(img)
        elif code == "FOLDER_ICON":
            folder_icon = "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMBAJqcGAAAAKNJREFUOI3t0jEOAVEUheFvhl1oaCyBWAmFXqWltRyFRKkVURClXsMaJEKMwkgeYgxaJ7l59+bd8+e85PGjoqCvoxLMe0xwzALEgbmLU1BlDPImaKWm0cP9DosM/zRCDW2c3yzfdMA47Ycxephh7v4Jr6of0orp+Rg9S61wiF9t5dUfcAUkX4BiFJBE6KCKVU5zE5sUsr595QZKH6bYYvmh51kX4x4kIG+YIVkAAAAASUVORK5CYII="
            img.LoadStream(StringIO(folder_icon.decode('base64')))
            del folder_icon
            return wx.BitmapFromImage(img)
        elif code == "FILES_ICON":
            files_icon = "iVBORw0KGgoAAAANSUhEUgAAAA0AAAAQCAYAAADNo/U5AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMBAJqcGAAAAK9JREFUKJGd0rEKgVEUAODvl91gMpgtBovyBLIoJZsX8EhKmcwm9T+AkYwyGUxKIS9g8eeP2/XnLPec0/06de9JvGOHs9/RyhfDAgDSBAdUC1xeY4C0jCMaBdAtS8qvc4xeBEzzRYaWSCPoEUIdtCNoFUInJBF0CaFSLg9FKYRqaEbQKYQ22EfQPYT66EbQ7LMRe+p8ZJ+bZpMmvndvjsVHb4TKP5MkuGJbANW9dvQJIwYbteCHXwcAAAAASUVORK5CYII="
            img.LoadStream(StringIO(files_icon.decode('base64')))
            del files_icon
            return wx.BitmapFromImage(img)        
        else:
            default = "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAIklEQVR42mNkoDFgHLVg1IJRC0YtGLVg1IJRC0YtGBoWAAB6xAAZ8ZgR7wAAAABJRU5ErkJggg=="
            img.LoadStream(StringIO(default.decode('base64'))) 
            del default
            return wx.StaticBitmap(self.parent, -1, wx.BitmapFromImage(img))
        